guid: "42d83eb8-b6b2-4b1b-b3d9-0c2f2b3b5a6c"
name: "Interactive Video Player"
description: "Interactive video player for Black Mirror: Bandersnatch with choice-based navigation and branching storylines"
overview: "Transform your Jellyfin into an interactive video experience with this plugin that adds choice-based navigation to Black Mirror: Bandersnatch. Features include keyboard controls, speed management, subtitle support, and state persistence across sessions."
owner: "deathrjj"
category: "General"
tags:
  - "interactive"
  - "video"
  - "bandersnatch"
  - "choices"
  - "player"
  - "keyboard-controls"
  - "subtitles"
nicename: "Interactive Video Player"
imageUrl: ""
version: "1.1.1"
jellyfinVersion: "10.8.0"
dotnetTarget: "net6.0"
framework: "netstandard2.1" 